version: '3.8'
services:
  mariadb:
    image: mariadb
    container_name: mariadb-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: springboot
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3307"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - spring-data

  voiture-app-backend:
    image: voiture-app-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voiture-app-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3307/springboot
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - spring-data

  voiture-front-end:
    image: voiture-app-frontend:latest  # Custom image name for the frontend
    build:
      context: ./src/main/webapp/reactjs  # Path to your frontend directory
      args:
        NODE_ENV: production  # Optional, can set environment variables for the build
    container_name: voiture-app-frontend
    ports:
      - "3000:80"
    networks:
      - spring-data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - voiture-app-backend
    networks:
      - spring-data

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - spring-data

volumes:
  mariadb_data:

networks:
  spring-data: